version: '3.7'
services:

  react:
    build:
      context: ./react
      dockerfile: Dockerfile-react
    ports:
      - "3000:3000"
    volumes:
      - ./react:/app
      - /app/node_modules
    networks:
      - app-network

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile-laravel
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: appdev_proj
      DB_USERNAME: root
      DB_PASSWORD: _MiniSQL_512
    volumes:
      - ./laravel:/var/www
    ports:
      - "8000:8000"
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: appdev_proj
      MYSQL_USER: root
      MYSQL_PASSWORD: _MiniSQL_512
      MYSQL_ROOT_PASSWORD: _MiniSQL_512
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "4306:4306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: _MiniSQL_512
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge