version: "3.7"
services:
  react:
    build:
      context: ./react
      dockerfile: Dockerfile-react
    ports:
      - "3000:3000"
    volumes:
      - ./react:/app
      - /app/node_modules
    networks:
      - app-network

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile-laravel
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 4306
      DB_DATABASE: appdev_proj
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./laravel:/var/www
    ports:
      - "8001:80"
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: appdev_proj
      MYSQL_ROOT_PASSWORD: _MiniSQL_512
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "4306:4306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - mysql

  apache:
    build:
      dockerfile: Dockerfile-apache
    ports:
      - "80:80"
    volumes:
      - ./apache:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
