FROM php:7.4-apache

# Install PHP extensions and enable Apache mods
RUN docker-php-ext-install pdo_mysql && a2enmod rewrite

# Copy application source
COPY . /var/www/html

# Set working directory
WORKDIR /var/www/html