# Dockerfile-laravel
FROM composer:2 as composer

WORKDIR /app

COPY . .

RUN composer update

FROM php:8.2-fpm

WORKDIR /var/www

COPY --from=composer /app /var/www

RUN docker-php-ext-install pdo_mysql
